/// Flutter icons Icons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icons
///      fonts:
///       - asset: fonts/Icons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'Icons';
  static const String? _kFontPkg = null;

  static const IconData listen = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifi_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData turnoff_mic = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finsh = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dowload_file = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData practice = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
